name: Test On Push

on:
  push:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x" # SDK Version to use.

      - name: Test
        run: dotnet test
